name: Make
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  make:
    name: Make
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Make
      run: ./make.sh
